kind: pipeline
type: kubernetes
name: spotidash
steps:
  - name: debug secret
    image: alpine
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    commands:
      - echo "$docker_username"
  - name: build and push docker image
    image: plugins/docker
    settings:
      repo: crowdsalat/spotidash
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
get:
  path: dockerhub
  name: username
---
kind: secret
name: docker_password
get:
  path: dockerhub
  name: password