version: "3"
services: 
    spotidash:
        container_name:  spotidash
        image: crowdsalat/spotidash:latest
        restart: always
        ports:
          - "10000:8080"
        environment:
          # pass environment variables
          - SPOTIFY_API_KEY
          - SPOTIFY_API_KEY_SECRET
          - CALLBACK_URI
